import Footer from "./components/layout/footer";
import MainHeader from "./components/layout/mainHeader";
import Notification from "./components/layout/notification";
import TopHeader from "./components/layout/topHeader";
import "./globals.css";
import { Roboto } from "next/font/google";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#faf9ff]`}>
        <TopHeader />
        <MainHeader />
        <Notification />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
